### ISSUE TITLE
Gem Versioning Issue

### ISSUE THREAD

**Issue by Babar-Livestorm** [jamesstonehill/api_error_handler#22]
Thanks you for the great work on the gem, I experienced the issue mentioned [here](https://github.com/jamesstonehill/api_error_handler/issues/21)

The gem version added is `0.1.0RC`.
Installing the gem by providing with the available tag `0.2.0` saying the repository doesn't have the version available and the closest match is `0.2.1` which once installed works flawlessly.

**Comment by jamesstonehill** [comment]
I've released version 0.2.1. Seems like I forgot to do that when fixing bugs a while back. Thanks for pointing out the issue!
